# Generated by Django 3.2.23 on 2024-01-20 09:49

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nickname_post',
            field=models.CharField(default=321, max_length=255, verbose_name=profiles.models.Profile),
            preserve_default=False,
        ),
    ]
