# Generated by Django 3.2.23 on 2024-02-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240119_1822'),
        ('posts', '0003_remove_post_nickname_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='posts_used_in', to='products.Product'),
        ),
    ]
