# Generated by Django 3.2.23 on 2024-02-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240119_1822'),
        ('posts', '0004_alter_post_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
