# Generated by Django 3.2.23 on 2024-02-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240119_1822'),
        ('profiles', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='products_used',
            field=models.ManyToManyField(related_name='used_by_users', to='products.Product'),
        ),
    ]
