# Generated by Django 3.2.23 on 2024-03-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../def_profile_t6zlys', upload_to='images/'),
        ),
    ]
