# Generated by Django 3.2.23 on 2024-01-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Nervous & Emotional', 'Nervous & Emotional'), ('Respiratory', 'Respiratory'), ('Digestive', 'Digestive'), ('Cardiovascular', 'Cardiovascular'), ('Urinary', 'Urinary'), ('Endocrine and Reproductive', 'Endocrine and Reproductive'), ('Lymphatic/Imune', 'Lymphatic/Imune'), ('Skin and connective tissues', 'Skin and connective tissues'), ('Muscles, bones, ligaments', 'Muscles, bones, ligaments')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='body_systems',
            field=models.ManyToManyField(to='products.BodySystem'),
        ),
    ]
