# Generated by Django 3.2.23 on 2024-01-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240119_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ailment',
            new_name='condition',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='../product_default_putkpj', upload_to='images/'),
        ),
    ]
